feat: add extraLabels to deployment
hashicorp/vault-secrets-operator pull request #281
Opened 2023-07-04 16:13 UTC by wwniclask25

The helm chart is currently missing an option to add additional labels to the deployment.

2023-07-04 16:13 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/vault-secrets-operator?pullRequest=281)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/vault-secrets-operator?pullRequest=281)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/vault-secrets-operator?pullRequest=281).</sub>

2023-07-10 18:25 UTC, kschoche requested changes
Hi @wwniclask25 -
Thanks for bringing this to our attention and submitting the PR.

Could you also please add bats testing to the `test/unit/deployment.bats` test to accomadate these changes?

Thanks!

2023-07-11 14:24 UTC, kschoche approved these changes
Looks good, thanks!

2023-07-31 07:30 UTC, wwniclask25 commented
@kschoche is there anything i need to do in order to get this merged? Seems like it still requires some test status

2023-08-10 16:06 UTC, merged